name: KinD Cluster CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      skip_checks:
        description: 'Skip checks'
        required: false
        default: 'false'

jobs:
  kind:
    runs-on: self-hosted  # use 'ubuntu-latest' only if hosted runners are enabled

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Install KinD
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.22.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Create KinD cluster
        run: kind create cluster --wait 60s

      - name: Verify cluster is up
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: Conditionally run checks
        if: ${{ github.event.inputs.skip_checks != 'true' }}
        run: |
          echo "Running pre-checks..."
          kubectl get pods --all-namespaces

      - name: Deploy test pod
        run: |
          echo "
          apiVersion: v1
          kind: Pod
          metadata:
            name: hello
          spec:
            containers:
            - name: hello
              image: busybox
              command: ['sh', '-c', 'echo Hello from Kubernetes! && sleep 30']
          " | kubectl apply -f -

      - name: Wait for pod to be ready
        run: kubectl wait --for=condition=Ready pod/hello --timeout=60s

      - name: Check pod status
        run: kubectl get pods

      - name: Delete KinD cluster
        if: always()
        run: kind delete cluster
